services:
  client:
    build:
      context: ./website/client
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:83:5173"
    volumes:
      - ./website/client:/app
    environment:
      - NODE_ENV=development
    command: sh -c "npm i && npm run docs:dev -- --port 5173 --host 0.0.0.0"

  server:
    build:
      context: ./website/server
      dockerfile: Dockerfile
    # No ports exposed to the host!
    volumes:
      - ./website/server:/app
    environment:
      - NODE_ENV=development
      - PORT=8080
    command: sh -c "npm i && npm run dev"
