[files]
extend-exclude = [
    "apps/web/client/.vitepress/config/*.ts",
    "apps/web/client/src/**/*.md",
    ".git",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "Việt Nam",
]

[default.extend-words]
# "styl" is the file extension for Stylus CSS preprocessor
styl = "styl"
