# Run website in optimized mode
# $ docker compose -f website/compose.yml up --build

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=production
    # override default command
    command: sh -c "npm i && npm run docs:dev -- --port 5173 --host"
    deploy:
      resources:
        limits:
          memory: 512M

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=production
      - PORT=8080
      - NODE_OPTIONS=--max-old-space-size=512
    # override default command
    command: sh -c "npm i && npm run dev"
    deploy:
      resources:
        limits:
          memory: 768M
    develop:
      watch:
        - action: sync+restart
          path: ./server
          target: /app
