name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  rust-test:
    name: Rust workspace tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.92.0
      - run: cargo test --workspace

  lint-biome:
    name: Lint Biome
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: legacy/repomix-ts
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .tool-versions
          cache: npm
          cache-dependency-path: legacy/repomix-ts/package-lock.json
      - run: npm ci
      - run: npm run lint-biome && git diff --exit-code

  lint-oxlint:
    name: Lint oxlint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: legacy/repomix-ts
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .tool-versions
          cache: npm
          cache-dependency-path: legacy/repomix-ts/package-lock.json
      - run: npm ci
      - run: npm run lint-oxlint && git diff --exit-code

  lint-ts:
    name: Lint TypeScript
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: legacy/repomix-ts
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .tool-versions
          cache: npm
          cache-dependency-path: legacy/repomix-ts/package-lock.json
      - run: npm ci
      - run: npm run lint-ts

  lint-secretlint:
    name: Lint Secretlint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: legacy/repomix-ts
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .tool-versions
          cache: npm
          cache-dependency-path: legacy/repomix-ts/package-lock.json
      - run: npm ci
      - run: npm run lint-secretlint

  lint-web-client:
    name: Lint Web Client
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: apps/web/client
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .tool-versions
          cache: npm
          cache-dependency-path: apps/web/client/package-lock.json
      - run: npm ci
      - run: npm run lint

  lint-legacy-web-server:
    name: Lint Legacy Web Server
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: legacy/website-server-ts
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .tool-versions
          cache: npm
          cache-dependency-path: legacy/website-server-ts/package-lock.json
      - run: npm ci
      - run: npm run lint

  lint-browser:
    name: Lint Browser Extension
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: legacy/repomix-ts/browser
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .tool-versions
          cache: npm
          cache-dependency-path: legacy/repomix-ts/browser/package-lock.json
      - run: npm ci
      - run: npm run prepare
      - run: npm run lint

  lint-action:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: rhysd/actionlint@a443f344ff32813837fa49f7aa6cbc478d770e62 # v1.7.9
        with:
          args: "-color"

  check-typos:
    name: Check typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: crate-ci/typos@2d0ce569feab1f8752f1dde43cc2f2aa53236e06 # v1.40.0

  test:
    name: Legacy TS tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20.x, 22.x, 24.x, 25.x]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: legacy/repomix-ts
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: legacy/repomix-ts/package-lock.json
      - run: npm ci
      - run: ./node_modules/.bin/vitest --reporter=verbose
        env:
          CI_OS: ${{ runner.os }}

  test-bun:
    name: Legacy TS tests with Bun
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        bun-version: [latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: legacy/repomix-ts
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: ${{ matrix.bun-version }}
      - run: bun install
      - run: bun run test
        env:
          CI_OS: ${{ runner.os }}

  test-coverage:
    name: Legacy TS coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: legacy/repomix-ts
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .tool-versions
          cache: npm
          cache-dependency-path: legacy/repomix-ts/package-lock.json
      - run: npm ci
      - run: npm run test-coverage -- --reporter=verbose
        env:
          CI_OS: ${{ runner.os }}
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: test-coverage
          path: legacy/repomix-ts/coverage/
      - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          fail_ci_if_error: true
          directory: ./legacy/repomix-ts/coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test-browser:
    name: Test Browser Extension
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: legacy/repomix-ts/browser
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .tool-versions
          cache: npm
          cache-dependency-path: legacy/repomix-ts/browser/package-lock.json
      - run: npm ci
      - run: npm run prepare
      - run: npm run test

  build-and-run:
    name: Legacy TS build and run
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20.x, 22.x, 24.x, 25.x]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: legacy/repomix-ts
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: legacy/repomix-ts/package-lock.json
      - run: npm ci
      - run: ./node_modules/.bin/rimraf lib && ./node_modules/.bin/tsc -p tsconfig.build.json --sourceMap --declaration
      - run: npm ci --omit=dev
      - run: node bin/repomix.cjs
      - run: node bin/repomix.cjs --version
      - run: node bin/repomix.cjs --help
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: repomix-output-${{ matrix.os }}-${{ matrix.node-version }}.txt
          path: legacy/repomix-ts/repomix-output.txt

  build-and-run-bun:
    name: Legacy TS build and run with Bun
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        bun-version: [latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: legacy/repomix-ts
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: ${{ matrix.bun-version }}
      - run: bun install
      - run: bun run build
      - run: bun install --production
      - run: bun bin/repomix.cjs
      - run: bun bin/repomix.cjs --version
      - run: bun bin/repomix.cjs --help
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: repomix-output-bun-${{ matrix.os }}-${{ matrix.bun-version }}.txt
          path: legacy/repomix-ts/repomix-output.txt
