name: Homebrew

on:
  release:
    types:
      - published
  workflow_call:
    inputs:
      publish_formula:
        description: Whether to bump the Homebrew formula
        required: false
        default: true
        type: boolean

jobs:
  homebrew:
    if: ${{ (github.event_name == 'workflow_call' && inputs.publish_formula) || (github.event_name == 'release' && !github.event.release.prerelease) }}
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          test-bot: false

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@main

      - name: Bump packages
        uses: Homebrew/actions/bump-packages@main
        with:
          token: ${{ secrets.COMMITTER_TOKEN }}
          formulae: repoxide
